# Prometheus configuration for Django Twilio Call Center monitoring

global:
  scrape_interval: 30s
  evaluation_interval: 30s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'django-twilio-call'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/observability/metrics/'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Health check endpoint
  - job_name: 'django-twilio-call-health'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/observability/health/detailed/'
    scrape_interval: 60s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics (optional)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis exporter (optional)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL exporter (optional)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']