apiVersion: v1
kind: ConfigMap
metadata:
  name: django-twilio-call-config
  namespace: django-twilio-call
  labels:
    app.kubernetes.io/name: django-twilio-call
    app.kubernetes.io/component: configuration
data:
  # Django configuration
  DJANGO_SETTINGS_MODULE: "callcenter.settings.production"

  # Database configuration
  DB_NAME: "callcenter"
  DB_USER: "callcenter_user"
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"

  # Redis configuration
  REDIS_URL: "redis://redis-service:6379/0"
  CELERY_BROKER_URL: "redis://redis-service:6379/1"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/2"

  # Twilio configuration
  TWILIO_WEBHOOK_VALIDATE: "true"
  TWILIO_REGION: "us1"

  # Django-Twilio-Call configuration
  DEFAULT_QUEUE: "support"
  RECORDING_ENABLED: "true"
  RECORDING_STORAGE: "s3"

  # Performance configuration
  GUNICORN_WORKERS: "4"
  GUNICORN_TIMEOUT: "30"
  CELERY_WORKER_CONCURRENCY: "4"

  # AWS configuration
  USE_AWS: "true"
  AWS_S3_REGION_NAME: "us-east-1"

  # CORS configuration
  CORS_ALLOWED_ORIGINS: "https://yourdomain.com,https://app.yourdomain.com"
  CSRF_TRUSTED_ORIGINS: "https://yourdomain.com,https://www.yourdomain.com"

  # Monitoring configuration
  SENTRY_TRACES_SAMPLE_RATE: "0.1"
  SENTRY_PROFILES_SAMPLE_RATE: "0.1"